version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:80"

  database:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
